/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DaysyUIDemoRouteImport } from './routes/daysyUI/demo'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as DemoAboutRouteImport } from './routes/demo/about'
import { Route as DemoPropsRouteImport } from './routes/demo/props'
import { Route as DemoUseIdRouteImport } from './routes/demo/useId'
import { Route as DemoUseImperativeHandleRouteImport } from './routes/demo/useImperativeHandle'
import { Route as DemoUseLayoutEffectRouteImport } from './routes/demo/useLayoutEffect'
import { Route as DemoUseTitleRouteImport } from './routes/demo/useTitle'
import { Route as TailwindActionRouteImport } from './routes/tailwind/action'
import { Route as TailwindColorRouteImport } from './routes/tailwind/color'
import { Route as TailwindLayoutRouteImport } from './routes/tailwind/layout'
import { Route as TailwindSizeAndSpaceRouteImport } from './routes/tailwind/sizeAndSpace'
import { Route as TailwindTestRouteImport } from './routes/tailwind/test'
import { Route as TailwindTextRouteImport } from './routes/tailwind/text'
import { Route as DemoPostPostIdRouteImport } from './routes/demo/post/$postId'
import { Route as DemoPostUseRefRouteImport } from './routes/demo/post/useRef'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DaysyUIDemoRoute = DaysyUIDemoRouteImport.update({
  id: '/daysyUI/demo',
  path: '/daysyUI/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAboutRoute = DemoAboutRouteImport.update({
  id: '/demo/about',
  path: '/demo/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPropsRoute = DemoPropsRouteImport.update({
  id: '/demo/props',
  path: '/demo/props',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoUseIdRoute = DemoUseIdRouteImport.update({
  id: '/demo/useId',
  path: '/demo/useId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoUseImperativeHandleRoute = DemoUseImperativeHandleRouteImport.update({
  id: '/demo/useImperativeHandle',
  path: '/demo/useImperativeHandle',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoUseLayoutEffectRoute = DemoUseLayoutEffectRouteImport.update({
  id: '/demo/useLayoutEffect',
  path: '/demo/useLayoutEffect',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoUseTitleRoute = DemoUseTitleRouteImport.update({
  id: '/demo/useTitle',
  path: '/demo/useTitle',
  getParentRoute: () => rootRouteImport,
} as any)
const TailwindActionRoute = TailwindActionRouteImport.update({
  id: '/tailwind/action',
  path: '/tailwind/action',
  getParentRoute: () => rootRouteImport,
} as any)
const TailwindColorRoute = TailwindColorRouteImport.update({
  id: '/tailwind/color',
  path: '/tailwind/color',
  getParentRoute: () => rootRouteImport,
} as any)
const TailwindLayoutRoute = TailwindLayoutRouteImport.update({
  id: '/tailwind/layout',
  path: '/tailwind/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const TailwindSizeAndSpaceRoute = TailwindSizeAndSpaceRouteImport.update({
  id: '/tailwind/sizeAndSpace',
  path: '/tailwind/sizeAndSpace',
  getParentRoute: () => rootRouteImport,
} as any)
const TailwindTestRoute = TailwindTestRouteImport.update({
  id: '/tailwind/test',
  path: '/tailwind/test',
  getParentRoute: () => rootRouteImport,
} as any)
const TailwindTextRoute = TailwindTextRouteImport.update({
  id: '/tailwind/text',
  path: '/tailwind/text',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPostPostIdRoute = DemoPostPostIdRouteImport.update({
  id: '/demo/post/$postId',
  path: '/demo/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPostUseRefRoute = DemoPostUseRefRouteImport.update({
  id: '/demo/post/useRef',
  path: '/demo/post/useRef',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/daysyUI/demo': typeof DaysyUIDemoRoute
  '/demo/about': typeof DemoAboutRoute
  '/demo/props': typeof DemoPropsRoute
  '/demo/useId': typeof DemoUseIdRoute
  '/demo/useImperativeHandle': typeof DemoUseImperativeHandleRoute
  '/demo/useLayoutEffect': typeof DemoUseLayoutEffectRoute
  '/demo/useTitle': typeof DemoUseTitleRoute
  '/tailwind/action': typeof TailwindActionRoute
  '/tailwind/color': typeof TailwindColorRoute
  '/tailwind/layout': typeof TailwindLayoutRoute
  '/tailwind/sizeAndSpace': typeof TailwindSizeAndSpaceRoute
  '/tailwind/test': typeof TailwindTestRoute
  '/tailwind/text': typeof TailwindTextRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/post/$postId': typeof DemoPostPostIdRoute
  '/demo/post/useRef': typeof DemoPostUseRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/daysyUI/demo': typeof DaysyUIDemoRoute
  '/demo/about': typeof DemoAboutRoute
  '/demo/props': typeof DemoPropsRoute
  '/demo/useId': typeof DemoUseIdRoute
  '/demo/useImperativeHandle': typeof DemoUseImperativeHandleRoute
  '/demo/useLayoutEffect': typeof DemoUseLayoutEffectRoute
  '/demo/useTitle': typeof DemoUseTitleRoute
  '/tailwind/action': typeof TailwindActionRoute
  '/tailwind/color': typeof TailwindColorRoute
  '/tailwind/layout': typeof TailwindLayoutRoute
  '/tailwind/sizeAndSpace': typeof TailwindSizeAndSpaceRoute
  '/tailwind/test': typeof TailwindTestRoute
  '/tailwind/text': typeof TailwindTextRoute
  '/demo': typeof DemoIndexRoute
  '/demo/post/$postId': typeof DemoPostPostIdRoute
  '/demo/post/useRef': typeof DemoPostUseRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/daysyUI/demo': typeof DaysyUIDemoRoute
  '/demo/about': typeof DemoAboutRoute
  '/demo/props': typeof DemoPropsRoute
  '/demo/useId': typeof DemoUseIdRoute
  '/demo/useImperativeHandle': typeof DemoUseImperativeHandleRoute
  '/demo/useLayoutEffect': typeof DemoUseLayoutEffectRoute
  '/demo/useTitle': typeof DemoUseTitleRoute
  '/tailwind/action': typeof TailwindActionRoute
  '/tailwind/color': typeof TailwindColorRoute
  '/tailwind/layout': typeof TailwindLayoutRoute
  '/tailwind/sizeAndSpace': typeof TailwindSizeAndSpaceRoute
  '/tailwind/test': typeof TailwindTestRoute
  '/tailwind/text': typeof TailwindTextRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/post/$postId': typeof DemoPostPostIdRoute
  '/demo/post/useRef': typeof DemoPostUseRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/daysyUI/demo'
    | '/demo/about'
    | '/demo/props'
    | '/demo/useId'
    | '/demo/useImperativeHandle'
    | '/demo/useLayoutEffect'
    | '/demo/useTitle'
    | '/tailwind/action'
    | '/tailwind/color'
    | '/tailwind/layout'
    | '/tailwind/sizeAndSpace'
    | '/tailwind/test'
    | '/tailwind/text'
    | '/demo/'
    | '/demo/post/$postId'
    | '/demo/post/useRef'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/daysyUI/demo'
    | '/demo/about'
    | '/demo/props'
    | '/demo/useId'
    | '/demo/useImperativeHandle'
    | '/demo/useLayoutEffect'
    | '/demo/useTitle'
    | '/tailwind/action'
    | '/tailwind/color'
    | '/tailwind/layout'
    | '/tailwind/sizeAndSpace'
    | '/tailwind/test'
    | '/tailwind/text'
    | '/demo'
    | '/demo/post/$postId'
    | '/demo/post/useRef'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/daysyUI/demo'
    | '/demo/about'
    | '/demo/props'
    | '/demo/useId'
    | '/demo/useImperativeHandle'
    | '/demo/useLayoutEffect'
    | '/demo/useTitle'
    | '/tailwind/action'
    | '/tailwind/color'
    | '/tailwind/layout'
    | '/tailwind/sizeAndSpace'
    | '/tailwind/test'
    | '/tailwind/text'
    | '/demo/'
    | '/demo/post/$postId'
    | '/demo/post/useRef'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DaysyUIDemoRoute: typeof DaysyUIDemoRoute
  DemoAboutRoute: typeof DemoAboutRoute
  DemoPropsRoute: typeof DemoPropsRoute
  DemoUseIdRoute: typeof DemoUseIdRoute
  DemoUseImperativeHandleRoute: typeof DemoUseImperativeHandleRoute
  DemoUseLayoutEffectRoute: typeof DemoUseLayoutEffectRoute
  DemoUseTitleRoute: typeof DemoUseTitleRoute
  TailwindActionRoute: typeof TailwindActionRoute
  TailwindColorRoute: typeof TailwindColorRoute
  TailwindLayoutRoute: typeof TailwindLayoutRoute
  TailwindSizeAndSpaceRoute: typeof TailwindSizeAndSpaceRoute
  TailwindTestRoute: typeof TailwindTestRoute
  TailwindTextRoute: typeof TailwindTextRoute
  DemoIndexRoute: typeof DemoIndexRoute
  DemoPostPostIdRoute: typeof DemoPostPostIdRoute
  DemoPostUseRefRoute: typeof DemoPostUseRefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daysyUI/demo': {
      id: '/daysyUI/demo'
      path: '/daysyUI/demo'
      fullPath: '/daysyUI/demo'
      preLoaderRoute: typeof DaysyUIDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/about': {
      id: '/demo/about'
      path: '/demo/about'
      fullPath: '/demo/about'
      preLoaderRoute: typeof DemoAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/props': {
      id: '/demo/props'
      path: '/demo/props'
      fullPath: '/demo/props'
      preLoaderRoute: typeof DemoPropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/useId': {
      id: '/demo/useId'
      path: '/demo/useId'
      fullPath: '/demo/useId'
      preLoaderRoute: typeof DemoUseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/useImperativeHandle': {
      id: '/demo/useImperativeHandle'
      path: '/demo/useImperativeHandle'
      fullPath: '/demo/useImperativeHandle'
      preLoaderRoute: typeof DemoUseImperativeHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/useLayoutEffect': {
      id: '/demo/useLayoutEffect'
      path: '/demo/useLayoutEffect'
      fullPath: '/demo/useLayoutEffect'
      preLoaderRoute: typeof DemoUseLayoutEffectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/useTitle': {
      id: '/demo/useTitle'
      path: '/demo/useTitle'
      fullPath: '/demo/useTitle'
      preLoaderRoute: typeof DemoUseTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailwind/action': {
      id: '/tailwind/action'
      path: '/tailwind/action'
      fullPath: '/tailwind/action'
      preLoaderRoute: typeof TailwindActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailwind/color': {
      id: '/tailwind/color'
      path: '/tailwind/color'
      fullPath: '/tailwind/color'
      preLoaderRoute: typeof TailwindColorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailwind/layout': {
      id: '/tailwind/layout'
      path: '/tailwind/layout'
      fullPath: '/tailwind/layout'
      preLoaderRoute: typeof TailwindLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailwind/sizeAndSpace': {
      id: '/tailwind/sizeAndSpace'
      path: '/tailwind/sizeAndSpace'
      fullPath: '/tailwind/sizeAndSpace'
      preLoaderRoute: typeof TailwindSizeAndSpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailwind/test': {
      id: '/tailwind/test'
      path: '/tailwind/test'
      fullPath: '/tailwind/test'
      preLoaderRoute: typeof TailwindTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailwind/text': {
      id: '/tailwind/text'
      path: '/tailwind/text'
      fullPath: '/tailwind/text'
      preLoaderRoute: typeof TailwindTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/post/$postId': {
      id: '/demo/post/$postId'
      path: '/demo/post/$postId'
      fullPath: '/demo/post/$postId'
      preLoaderRoute: typeof DemoPostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/post/useRef': {
      id: '/demo/post/useRef'
      path: '/demo/post/useRef'
      fullPath: '/demo/post/useRef'
      preLoaderRoute: typeof DemoPostUseRefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DaysyUIDemoRoute: DaysyUIDemoRoute,
  DemoAboutRoute: DemoAboutRoute,
  DemoPropsRoute: DemoPropsRoute,
  DemoUseIdRoute: DemoUseIdRoute,
  DemoUseImperativeHandleRoute: DemoUseImperativeHandleRoute,
  DemoUseLayoutEffectRoute: DemoUseLayoutEffectRoute,
  DemoUseTitleRoute: DemoUseTitleRoute,
  TailwindActionRoute: TailwindActionRoute,
  TailwindColorRoute: TailwindColorRoute,
  TailwindLayoutRoute: TailwindLayoutRoute,
  TailwindSizeAndSpaceRoute: TailwindSizeAndSpaceRoute,
  TailwindTestRoute: TailwindTestRoute,
  TailwindTextRoute: TailwindTextRoute,
  DemoIndexRoute: DemoIndexRoute,
  DemoPostPostIdRoute: DemoPostPostIdRoute,
  DemoPostUseRefRoute: DemoPostUseRefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
